name: Continues_Deployment

on:
  workflow_run:
    workflows: ['Continues_Integration']
    types:
      - completed
    branches: master

jobs:
  deploy_on_cache:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Download production artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-to-prod

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GETTHINGSDONE_391622 }}'
          projectId: getthingsdone-391622
          channelId: '${ git describe --tags `git rev-list --tags --max-count=1` }'
