name: Continues_Deployment

on:
  push:
    tags:
      - '*'

jobs:
  deploy_on_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Download production artifact
        uses: aochmann/actions-download-artifact@1.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: dist-to-prod

      - name: Calculate channel id
        id: tag
        uses: devops-actions/action-get-tag@v1.0.2
        with:
          default: v0.0.0

      - name: Create Release
        id: create_release
        uses: surmon-china/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body_path: 'CHANGELOG.md'
          draft: false
          prerelease: false

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GETTHINGSDONE_391622 }}'
          projectId: getthingsdone-391622
          channelId: ${{steps.tag.outputs.tag}}
