name: Continues Integration

on:
  push:
    branches:
      - 'master'

jobs:
  install-dep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies with Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn

  lint:
    runs-on: ubuntu-latest

    needs: install-dep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run Lint with Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn lint-check

  test:
    runs-on: ubuntu-latest

    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run Test with Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

  build:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run Build with Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn build

  version:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Configure commiter
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
  
      - name: Generate Version
        run: |
          yarn standard-version

      - name: Pushing Version
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git commit --allow-empty -m "[skip ci]"
          git push --follow-tags origin master
